<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Accueil</title>
</head>
<body class="">
 
    <!-- Image Map Generated by http://www.image-map.net/ -->
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
  <h1 class="mt-4 text-success">Accueil</h1>   
  <form class="d-flex" action="index.php">
    <input type="text" class="form-control me-2" name="nom" placeholder="Rechercher un élément">

    <input type="submit" class="btn btn-outline-success" value="Rechercher">
</form>
  </div>
</nav>
<div class="container">
    <!-- <img src="https://medias.pourlascience.fr/api/v1/images/view/5a82b0b18fe56f4a445484ed/wide_1300/image.jpg" usemap="#image-map">

<map name="image-map">
    <area target="" alt="Or" title="Or" href="http://localhost/php-pdo/PDO-MVC-PDO-CRUD/?page=element&id=3" coords="817,498,759,431" shape="rect">
    <area target="" alt="Fer" title="Fer" href="http://localhost/php-pdo/PDO-MVC-PDO-CRUD/?page=element&id=4" coords="614,348,559,285" shape="rect">
    <area target="" alt="Plomb" title="Plomb" href="http://localhost/php-pdo/PDO-MVC-PDO-CRUD/?page=element&id=1" coords="1015,496,962,434" shape="rect">
    <area target="" alt="Etain" title="Etain" href="http://localhost/php-pdo/PDO-MVC-PDO-CRUD/?page=element&id=2" coords="959,422,1015,360" shape="rect">
</map> -->
<a href="?page=element" class="m-4 btn btn-primary"> Liste</a>

</div>

</body>
</html>